// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package go_micro_srv_order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	UserId
	OrderDetail
	Orders
*/
package go_micro_srv_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户ID
type UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *UserId) Reset()                    { *m = UserId{} }
func (m *UserId) String() string            { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()               {}
func (*UserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 返回订单详情
type OrderDetail struct {
	// 订单Id
	OrderId int64 `protobuf:"varint,1,opt,name=OrderId" json:"OrderId,omitempty"`
	// 订单号
	OrderNum string `protobuf:"bytes,2,opt,name=OrderNum" json:"OrderNum,omitempty"`
}

func (m *OrderDetail) Reset()                    { *m = OrderDetail{} }
func (m *OrderDetail) String() string            { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()               {}
func (*OrderDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

// 返回订单
type Orders struct {
	Orders []*OrderDetail `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *Orders) Reset()                    { *m = Orders{} }
func (m *Orders) String() string            { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()               {}
func (*Orders) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Orders) GetOrders() []*OrderDetail {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*UserId)(nil), "go.micro.srv.order.UserId")
	proto.RegisterType((*OrderDetail)(nil), "go.micro.srv.order.OrderDetail")
	proto.RegisterType((*Orders)(nil), "go.micro.srv.order.Orders")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0x82, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xa1, 0xf4, 0x7c,
	0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0x3d, 0xb0, 0x8c, 0x92, 0x02, 0x17,
	0x5b, 0x68, 0x71, 0x6a, 0x91, 0x67, 0x8a, 0x90, 0x18, 0x17, 0x5b, 0x29, 0x98, 0x25, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x29, 0x39, 0x73, 0x71, 0xfb, 0x83, 0x94, 0xba, 0xa4, 0x96,
	0x24, 0x66, 0xe6, 0x08, 0x49, 0x70, 0xb1, 0x83, 0xb9, 0x50, 0x75, 0xcc, 0x41, 0x30, 0xae, 0x90,
	0x14, 0x17, 0x07, 0x98, 0xe9, 0x57, 0x9a, 0x2b, 0xc1, 0x04, 0x36, 0x02, 0xce, 0x57, 0x72, 0xe4,
	0x62, 0x03, 0xb3, 0x8b, 0x85, 0xcc, 0xb9, 0xd8, 0xc0, 0x36, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6b,
	0x70, 0x1b, 0xc9, 0xeb, 0x61, 0xba, 0x4a, 0x0f, 0xc9, 0xc2, 0x20, 0xa8, 0x72, 0xa3, 0x30, 0x2e,
	0x56, 0xb0, 0xb0, 0x90, 0x2f, 0x97, 0xa0, 0x5b, 0x66, 0x5e, 0x0a, 0x98, 0xe3, 0x54, 0x09, 0x75,
	0xbd, 0x14, 0x36, 0x63, 0x20, 0x72, 0x52, 0x52, 0x38, 0xad, 0x28, 0x56, 0x62, 0x48, 0x62, 0x03,
	0x07, 0x8e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x9a, 0xbb, 0xdb, 0x37, 0x01, 0x00, 0x00,
}
